-- 0005_a2a: durable A2A tasks.
--
-- The A2A SDK ships an in-memory task store. A task that vanishes on restart is
-- worse than no task store at all: a peer agent holds a task id we have already
-- promised to honour, and `GetTask` starts answering TASK_NOT_FOUND for work we
-- actually did. So the task lives in Postgres, under the same RLS as everything
-- else.
--
-- One jsonb column holds the whole `a2a::Task`, and nothing is copied out of it
-- into its own column. Duplicating `contextId` or `status.state` alongside the
-- document is how the two spellings drift; the filters below read the document
-- and the index below indexes the expression.

create table if not exists a2a_tasks (
  -- The A2A task id: a string on the wire, generated by us (UUIDv7), but a
  -- continuation carries whatever the peer sent, so the length is bounded here
  -- rather than trusted there.
  id           text        primary key,
  tenant_id    uuid        not null references tenants (id) on delete cascade,
  -- The employee that owns the A2A endpoint the peer reached.
  employee_id  uuid        references employees (id) on delete set null,
  -- Bumped on every update. The SDK's TaskStore hands back a version but never
  -- passes one in, so this is a change counter, not a lock.
  version      bigint      not null default 1,
  task         jsonb       not null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  constraint a2a_tasks_id_length check (char_length(id) between 1 and 200)
);

-- ponytail: one expression index, for the only filter `ListTasks` supports that
-- is not the primary key. Add one on `(task->'status'->>'state')` the day a
-- status filter shows up in a slow query log, not before.
create index if not exists a2a_tasks_context_idx
  on a2a_tasks (tenant_id, (task ->> 'contextId'));

alter table a2a_tasks enable row level security;
alter table a2a_tasks force row level security;
drop policy if exists tenant_isolation on a2a_tasks;
create policy tenant_isolation on a2a_tasks
  using (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid)
  with check (tenant_id = nullif(current_setting('app.tenant_id', true), '')::uuid);

grant select, insert, update, delete on a2a_tasks to app_role;
